image: python:3.7-alpine

stages:
  - run
  - test
  - deploy

before_script:
  - export PATH=/root/.local/bin:$PATH
  - pip install --user -U .


run:
  stage: run
  script:
    - recap

test:
  stage: test
  script:
    - pip install --user -U .[test]
    - pytest tests --cov recap

deploy:
  stage: deploy
  script:
    - pip install --user --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - twine upload --skip-existing --repository-url "$PYPI_REPOSITORY_URL" -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    - master
