image: python:3.7-alpine

stages:
  - test
  - deploy

before_script:
  - export PATH=/root/.local/bin:$PATH
  - pip install --user -U .

test:
  stage: test
  script:
    - pip install --user -U .[test]
    - pytest tests --cov recap

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install --user --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/*
